"""empty message

Revision ID: 18409f046c64
Revises: fdb279b2ac99
Create Date: 2026-09-11 19:16:24.321261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18409f046c64'
down_revision = 'fdb279b2ac99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_category', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_category_pid_name', ['pid', 'name'])
        batch_op.create_foreign_key(None, 't_category', ['pid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_category_pid_name', type_='unique')

    # ### end Alembic commands ###
